ARG IMAGE_NAME
ARG TAG
ARG REPO
FROM       prom/prometheus:latest

COPY       ./conf/alert.rules.yml  /etc/prometheus/alert.rules.yml
COPY       ./conf/prometheus.yml  /etc/prometheus/prometheus.yml
USER       root
EXPOSE     9090
VOLUME     [ "/prometheus" ]
WORKDIR    /prometheus
ENTRYPOINT [ "/bin/prometheus" ]
CMD        [ "--config.file=/etc/prometheus/prometheus.yml", \
             "--storage.tsdb.path=/prometheus", \
             "--web.console.libraries=/usr/share/prometheus/console_libraries", \
             "--web.console.templates=/usr/share/prometheus/consoles" , \
             "--storage.tsdb.retention=200h" , \
             "--web.enable-lifecycle" ]